### ISSUE TITLE
Filter out Serialnumbers via Prefix

### ISSUE THREAD

**Issue by floriangrotz** [pgerke/homebridge-freeathome-local-api#62]
**Is your feature request related to a problem? Please describe:**
I have Hueactors - starting with Serial #BEE
They are shown via the Plugin in Homekit

<img width="248" alt="hue_bee" src="https://user-images.githubusercontent.com/63972904/226167177-1773805b-8b7c-4d23-8502-bd5b36c6397d.png">

![IMG_1294](https://user-images.githubusercontent.com/63972904/226167194-1d37c917-9608-48d0-bea3-2b6a84be4788.jpeg)

![IMG_1295](https://user-images.githubusercontent.com/63972904/226167278-d38b5cd3-fd47-48b6-be59-d4f592fd328d.jpeg)

**Describe the solution you'd like:**
Possibility to filter out certain Prefixes - like BEE
Already pointed out in #48 

**Describe alternatives you've considered:**
removing in mappings - but it is a lot of effort

**Comment by pgerke** [comment]
Looking at https://github.com/pgerke/homebridge-freeathome-local-api/blob/162eb581c7f1b8ae69c50a94967a819060b5934b/src/platform.ts#L221 and the following lines, your Hue actuators should be skipped during discovery. 

This is probably related to accessories that are already cached in Homebridge. At the moment, they are exempt from the checks that are done during discovery. This is intentional, because I'd rather not remove accessories the user might have configured already (e.g. assigned to rooms, used in automations, ...). When an accessory is removed all those settings are deleted as well which might cause a lot of effort.

Would the `Remove Single Cached Accessory` option from the Homebridge settings solve your issue?

**Comment by floriangrotz** [comment]
Did fix the issue - thanks !
